version: '3.4'

x-common-variables: &common-variables
  S3_HOST: "s3:9000"
  S3_ACCESS_KEY: "minio"
  S3_ACCESS_SECRET: "miniominio"
  S3_BUCKET_NAME: "default_bucket"
  POSTGRES_DB: defaultapp
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: db
  ENVIRONMENT: local
  
x-app: &default-app
  build: ./appimage
  volumes:
    - ./appimage/baseapp:/code/baseapp
  networks:
    - backend

services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniominio
    volumes:
      - ./data/s3:/data
    command: server /data --console-address ":9090"
    networks:
      - backend
        
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    environment:
      <<: *common-variables
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
        - backend

  elastic:
    image: "elasticsearch:7.14.1"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - backend

  app:
    <<: *default-app
    environment:
      <<: *common-variables
    ports:
      - "8000:8000"

  tailwind:
    <<: *default-app
    command: /bin/sh /code/baseapp/run_tailwind.sh
    tty: true
      
networks:
  backend:
    driver: "bridge"
    